name: 'GET & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Whether to use chaching or not'
    required: false
    default: 'true'
runs:
    using: 'composite'
    steps:
        - name: Cache dependencies
          if: inputs.caching == 'true'
          id: cache
          uses: actions/cache@v3
          with:
            path: node_modules
            key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
        - name: Install dependecies
          if: steps.cache.outputs.cachce-hit != 'true' || inputs.caching != 'true'
          run: npm ci
          run: echo teps.cache.outputs.cachce-hit
          shell: bash
