name: 'GET & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Whether to use chaching or not'
    required: false
    default: 'true'
outputs:
  used-chache:
    description: 'Whether the cache is used or not'
    value: ${{steps.install.outputs.cache}}
runs:
    using: 'composite'
    steps:
        - name: Cache dependencies
          if: inputs.caching == 'true'
          id: cache
          uses: actions/cache@v3
          with:
            path: node_modules
            key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
        - name: Install dependecies
          id: install
          if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
          run: | 
            npm ci 
            echo "cache='${{inputs.caching}}'"
          shell: bash
